// ---------------------------------------------------------------------------------------------------------//
// ------------------------------------------------- MEDALS ------------------------------------------------//
// ---------------------------------------------------------------------------------------------------------//

App.Medal.FIXTURES = [
	{
		id: 100,
		name: "Hero of the Soviet Union",
		copy: "The highest military or civilian honor awarded for a heroic act.*",
		battles: [],
		veterans: [5,27,41,42,46,49],
	},
	{
		id: 101,
		name: "Order of the Patriotic War (1st and 2nd Class)",
		copy: "Given to all members of the Soviet Armed Forces that participated in World War 2.",
		battles: [],
		// Use this line to include all veteran ids
		// Change Veteran to Medal to perform same action on the medal model
		veterans: App.Veteran.FIXTURES.map(function(object) { return object.id; }),
	},
	{
		id: 102,
		name: "Order of the Red Star",
		copy: "Awarded to Red Army personnel for exceptional service in defense of the Soviet Union in war or peace time.",
		battles: [],
		veterans: [15,18,8,35,9,4,40,19,38,12,36],
	},
	{
		id: 103,
		name: "Order of the Red Banner",
		copy: "Awarded in recognition of an extraordinary military deed.",
		battles: [],
		veterans: [12],
	},
	{
		id: 104,
		name: "Order of Glory",
		copy: "Awarded to soldiers for bravery. Recipients move from bronze, to silver, to gold with each heroic act.",
		battles: [],
		veterans: [12,17,30],
	},
	{
		id: 105,
		name: "Medal for Courage",
		copy: "Similar to the Order of Glory though slightly less prestigious and typically awarded in defensive situations.",
		battles: [],
		veterans: [6,2,9,10,11,17,19,40],
	},
	{
		id: 106,
		name: "Medal for Battle Merit",
		copy: "Awarded for combat action resulting in military success.",
		battles: [],
		veterans: [16,40,10,19,26,4,7],
	},
	{
		id: 107,
		name: "Medal for Partisan of the Patriotic War (1st and 2nd Class)",
		copy: "Given to all partisans who fought on the Soviet side without being official members of the armed forces.",
		battles: [],
		veterans: [3,7,10,25,28],
	},
	{
		id: 108,
		name: "Medal for Defense of Leningrad",
		copy: "Awarded to all personnel who contributed to the defense of Leningrad.",
		battles: [200],
		veterans: [22,33],
	},
	{
		id: 109,
		name: "Medal For Defense of Stalingrad",
		copy: "Awarded to all personnel who contributed to the defense of Stalingrad.",
		battles: [203],
		veterans: [23,2,12,35,15,9],
	},
	{
		id: 110,
		name: "Medal For Defense of Moscow",
		copy: "Awarded to all personnel who contributed to the defense of Moscow.",
		battles: [201],
		veterans: [26,34,35],
	},
	{
		id: 111,
		name: "Medal For Defense of Kiev",
		copy: "Awarded to all personnel who contributed to the defense of Kiev.",
		battles: [],
		veterans: [44],
	},
	{
		id: 112,
		name: "Medal For Capture of Berlin",
		copy: "Awarded to all personnel who contributed to the capture of Berlin.",
		battles: [202],
		veterans: [20,36],
	},
	{
		id: 113,
		name: "Medal For Capture of Budapest",
		copy: "Awarded to all personnel who contributed to the capture of Budapest.",
		battles: [207],
		veterans: [12],
	},
	{
		id: 114,
		name: "Medal For Capture of Konigsberg",
		copy: "Awarded to all personnel who contributed to the capture of Konigsberg.",
		battles: [204],
		veterans: [6,2,10,28,34],
	},
	{
		id: 115,
		name: "Medal For Capture of Prague",
		copy: "Awarded to all personnel who contributed to the capture of Prague.",
		battles: [206],
		veterans: [23],
	},
	{
		id: 116,
		name: "Medal For Liberation of Warsaw",
		copy: "Awarded to all personnel who contributed to the capture of Warsaw.",
		battles: [],
		veterans: [23,11],
	},
	{
		id: 117,
		name: "Medal For Victory over Japan",
		copy: "Awarded to all personnl who contributed to the soviet campaign in Asia.",
		battles: [209],
		veterans: [32,45],
	},
	{
		id: 118,
		name: "Medal For Victory over Vienna",
		copy: "Awarded to all personel who contributed to the capture of Vienna. ",
		battles: [],
		veterans: [12,18,15],
	},
	{
		id: 119,
		name: "Order of Victory",
		copy: "Awarded to Generals for orchestrating a 'radical change in situation in favour of The Red Army'. It is the rarest medal with only 20 recipients. Made with rubies, platinum, and 150 diamonds, the medal itself is priceless.",
		battles: [],
		veterans: [46,50,49,48],
	},
	{
		id: 120,
		name: "People's Artist Of The USSR",
		copy: "Awarded for outstanding contribution to the performing arts",
		battles: [],
		veterans: [55],
	},
	{
		id: 121,
		name: "Liberation of Riga",
		copy: "Awarded to all personel who contributed to the Liberation of Riga",
		battles: [],
		veterans: [26, 40],
	},
	{
		id: 122,
		name: "Victory over Germany",
		copy: "Awarded for victory over Germany",
		battles: [],
		veterans: [11, 32, 41],
	},
	{
		id: 123,
		name: "Liberation of Vienna",
		copy: "Awarded for the Liberation of Vienna",
		battles: [],
		veterans: [15, 42],
	},
	{
		id: 125,
		name: "Battle of Stalingrad",
		copy: "Awarded to all personel who contributed to the Battle of Stalingrad.",
		battles: [203],
		veterans: [2],
	},
	{
		id: 126,
		name: "Battle of Danzig",
		copy: "Awarded to all personel who contributed to the Battle of Danzig.",
		battles: [],
		veterans: [2],
	},
	{
		id: 127,
		name: "Liberation Of Caucuses And Crimea",
		copy: "Awarded to all personel who contributed to the Battle of Danzig.",
		battles: [],
		veterans: [2, 15],
	},
	{
		id: 128,
		name: "Medal for the Capture Of New Lands",
		copy: "Awarded to all personel who contributed to the Battle of Danzig.",
		battles: [],
		veterans: [35],
	}
];
