// ------------------------------------------------------------------------------------------------------------//
// ------------------------------------------------- VETERANS -------------------------------------------------//
// ------------------------------------------------------------------------------------------------------------//

App.Veteran.FIXTURES = [
	{
		id: 1,
		name: "Alexi Litvachuk",
		date: "Born 1921 Vinnitsa, Ukraine.",
		info: "Communications - Eastern Front, Kishinev, Defense Of Moscow.",
		medals: [101],
	},
	{
		id: 2,
		name: "Alexi Shtern",
		date: "Born June 24th 1922 Odessa, Ukraine.",
		info: "Sergeant Major in tank unit: Battle Of Stalingrad, Danzig, And Capture Of Konigsberg",
		medals: [101,105, 109, 114, 125, 126, 122],
	},
	{
		id: 3,
		name: "Anna Khaliavskaya",
		date: "Born March 20th 1924 Minsk, Belarus.",
		info:  "Belarusian Partisan",
		medals: [107, 101],
	},
	{
		id: 4,
		name: "Arkadiy Novokolsky",
		date: "Born 1921 Odessa, Ukraine.",
		info: "Air Force Pilot And Engineer - Defense of Moscow",
		medals: [101,102, 106],
	},
	{
		id: 5,
		name: "Berta Tsirkina",
		date: "Born January 1935 Leningrad, Soviet Union.",
		info: "Siege Of Leningrad Survivor.",
		medals: [100, 101],
		youtube_id: "vcrMrF3BDXI",
	},
	{
		id: 6,
		name: "Boris Kravitz",
		date: "Born 1927 Noravlla, Belarus.",
		info: "Private In Border Detachment - Lithuania, Belarus, Konigsberg: One of 3 Jews to work at NKVD (precursor to KGB) investigating POWs for war crimes at a camp near Minsk",
		medals: [101,105, 114],
	},
	{
		id: 7,
		name: "Danil Zharnitsky",
		date: "Born May 19th 1927 Illyntsy, Ukraine.",
		info: "Partisan that became sniper in Red Army, served for 22 years working in SMERSH (Counter Intelligence Department) and Contruction Battalion",
		medals: [101,109, 107, 106],
	},
	{
		id: 8,
		name: "David Fisherman",
		date: "Born April 6th 1915 Tiraspol, Moldov.",
		indo: "Mechanic/Driver Light Tank Brigade - Defence Of Caucuses And Vitebsk Liberations Of Lithuania And Riga",
		medals: [101, 102],
		youtube_id: "LAn3DohZlgs",
	},
	{
		id: 9,
		name: "Efim Perlitch",
		date: "Born 1927 Malin, Ukraine.",
		info: "Infantry And Paratrooper - Stalingrad, Caucuses, Crimea",
		medals: [101,105,109],
		youtube_id: "xudC1nRvxSI",
	},
	{
		id: 10,
		name: "Eugene Kats",
		date: "Born January 6 1925 Desna, Poland.",
		info: "Polish Partisans, Heavy Machine Gun Division",
		medals: [101,107,105, 106, 114],
	},
	{
		id: 11,
		name: "Filipp Potievsky",
		date: "Born August 6th 1922 Malin, Ukraine.",
		info: "Wounded Near Moscow And Was Rescued By Famer Before Returning To Red Army",
		medals: [101,105,116,102],
		youtube_id: "_d4GtrR2WZk",
	},
	{
		id: 12,
		name: "Grigory Genin",
		date: "Born March 8th 1924 in Astrakhan, Soviet Union.",
		info: "Platoon Commander 550 Rifle Regiment Battle of Stalingrad, Fought near Odessa, in Romania, and Bulgaria, Liberations of Vienna and Budapest",
		medals: [101,109, 118, 113, 102, 104, 103],
	},
	{
		id: 13,
		name: "Grigory Svirsky",
		date: "Born September 29th 1921 Ufa, Soviet Union.",
		info: "Air Force Mechanic And Gunner Based Near Arctic Sea. Well Known In Russia For WWII Books And Social Criticism - Works Banned In 1968 And He Was Forced To Leave In 1972.",
		medals: [101,],
		youtube_id: "-qPek3t137o",
	},
	{
		id: 14,
		name: "Isaak Ashmian",
		date: "Born December 19th 1919 Kharkov, Ukraine (raised in Moscow).",
		info: "Volunteer Engineer Lieutenant Military Construction Corps, Moscow and Belarusian Front",
		medals: [101],
		youtube_id: "rJT-I-f2Wvg",
	},
	{
		id: 15,
		name: "Isaak Budnitsky",
		date: "Born April 29th 1918 Vasilkov, Ukraine.",
		info: "Sergeant Major 255th Aviation Service Regiment, Battle of Stalingrad, Crimea, Liberation Of Vienna",
		medals: [109, 101, 102, 123],
		youtube_id: "8CGypoTOzlQ",
	},
	{
		id: 16,
		name: "Isaak Kogan",
		date: "Born March 20th 1926 Rakitnoyeye, Ukraine",
		info: "Submachine gunner on 2nd Belorussian Front",
		medals: [101, 106],
	},
	{
		id: 17,
		name: "Isaak Zarembo",
		date: "Born on June 29th 1925 Kraslovo, Latvia",
		info: "Private 43rd Latvian Guards Division. Participated In Defense of Moscow and Liberation of Riga",
		medals: [101,105, 104],
	},
	{
		id: 18,
		name: "Lazar Chukhovich",
		date: "Born November 13th 1926 Tashkent, Uzbekistan.",
		info: "Sniper - 41st Guards Division. Ukrainian Front and Liberation Of Budapest",
		medals: [101,102],
		youtube_id: "9V27QtAJKe0",
	},
	{
		id: 19,
		name: "Leonid Feldman",
		date: "Born 1919 In Bershad Ukraine",
		info: "Master Sergeant Communications Platoon 5th Armoured Landing Division. Lieutenant Colonel By End Of The War: Leningrad, Konigsberg, Riga",
		medals: [102, 101, 106, 105],
	},
	{
		id: 20,
		name: "Leonid Sheinker",
		date: "Born March 6th 1920 in Tashkent, Uzbekistan",
		info: "Air Force Engineer and Gunner. Fought in Defense of Moscow and Capture of Berlin",
		medals: [101,112],
	},
	{
		id: 21,
		name: "Lev Pikus",
		date: "Born May 1st 1927 Minsk, Belarus",
		info: "Brest Partisans",
		medals: [101],
		youtube_id: "nV5JInaRMT4",
	},
	{
		id: 22,
		name: "Liya Liberova",
		date: "Born 1923 Novozybkov, Soviet Union",
		info: "Senior Sergeant - Anti air defense Leningrad",
		medals: [101,108],
	},
	{
		id: 23,
		name: "Losif Zibenberg",
		date: "Born April 30th 1922 Faleshty Bessarabia (present day Moldova)",
		info: "Private in communications platoon in armoured landing division (paratrooper). Stalingrad, Kursk, Liberation of Prague",
		medals: [101,115, 109],
		youtube_id: "fE_7MHPehis",
	},
	{
		id: 24,
		name: "Mark Bass",
		date: "Born December 25th 1922 Smolensk, Soviet Union.",
		info: "Member of The Moscow Motorcycle Battalion. Later served In Mongolia",
		medals: [101],
		youtube_id: "Q3pPGAILs6s",
	},
	{
		id: 25,
		name: "Mikhail Bass",
		date: "Born March 16th 1928 Mink, Belarus",
		info: "Belarusian Partisans, later joined Red Army. Fought in Poland and at Capture Of Konigsberg",
		medals: [101, 107],
		youtube_id: "HesaMLmmnGk",
	},
	{
		id: 26,
		name: "Moisei Chernoguz",
		date: "Born December 15th 1923 Sovran, Ukraine.",
		info: "Radio Operator 30th Attack Army. Placed in command of recently released convicts, fighting in war for reduced sentences",
		medals: [101,110, 106, 116],
		youtube_id: "FMfgxmCle_o",
	},
	{
		id: 27,
		name: "Nina Goldstein",
		info: "Siege Of Leningrad Survivor.",
		medals: [101,100,101],
	},
	{
		id: 28,
		name: "Noah Shneidman",
		date: "Born September 24th 1924 in Vilno, Poland (now Vilnus Lithuania).",
		info: "Front Line Infantry - Polish Partisans, Capture of Konigsberg and Berlin.",
		medals: [101,107, 114],
		youtube_id: "RGQMoxf8D0c",
	},
	{
		id: 29,
		name: "Semen Perlamutrov",
		date: "Born March 1 1920 Ukraine.",
		info: "Private in anti tank artillery - Siege Of Leningrad",
		medals: [101],
	},
	{
		id: 30,
		name: "Shelma Mushkat",
		date: "Born 1919 Sarkovshizno, Poland.",
		info: "Artillery Commander - Leningrad, Continuation War, Mongolia.",
		medals: [101,104],
	},
	{
		id: 31,
		name: "Shulim Grinberg",
		date: "Born February 21st 1922 Rybnitsa, Moldova.",
		info: "Air Force Gunner And Mechanic - Defence Of Moscow Battle Of Kursk.",
		medals: [102, 101, 106],
	},
	{
		id: 32,
		name: "Sima Vesoli",
		date: "Born January 1st 1923 Gomel, Belarus.",
		info: "Nurse - Germany And North Korea.",
		medals: [101,117, 122],
	},
	{
		id: 33,
		name: "Valentin Rabinovich",
		date: "Born December 25th 1922 in Riga, Latvia.",
		info: "Anti aircraft battalion helped break Siege Of Leningrad.",
		medals: [101,108],
		youtube_id: "FQ_ShgyQoJM",
	},
	{
		id: 34,
		name: "Venyamin Frumkin",
		date: "Born 1922 In Smolensk, Soviet Union.", 
		info: "Regiment Engineer - Defence Of Moscow, Capture Of Konigsberg, Advisor to North Korean Army.",
		medals: [110,114, 102, 101],
		youtube_id: "jEc7S6zeX2g",
	},
	{
		id: 35,
		name: "Yakov Gelfandbein",
		date: "Born 1922 Kherson, Ukraine.",
		info: "2nd Leningrad Artillery Corps And Later Paratrooper. Defence Of Leningrad, Battle Of Stalingrad, Ukrainian Front, Liberation Of Auschwitz",
		medals: [106,109, 110, 102, 101],
	},
	{
		id: 36,
		name: "Yakov Kreinin",
		info: "Katyusha (rockets) Platoon Commander 303 Guards Mortar Regiment: Ukraine, Poland, Kharkov, Capture of Berlin",
		medals: [102,101,112],
	},
	{
		id: 37,
		name: "Yakov Perlamutrov",
		info: "Machine Gunner: Ukrainian Front and Battle of Kursk.",
		medals: [101],
		youtube_id: "B-kaqE4-bKw",
	},
	{
		id: 38,
		name: "Yakov Rats",
		date: "Born May 28th 1923 Vitebsk, Belarus (moved to Leningrad as a baby).",
		info: "Tank Repair Instructor whose family survived Siege Of Leningrad.",
		medals: [101, 102],
	},
	{
		id: 40,
		name: "Yefim Feldman",
		date: "Born June 27 1923.",
		info: "Paramedic In Light Artillery Unit, Liberation of Riga",
		medals: [101,102, 106, 105,121],
	},
	{
		id: 41,
		name: "Yevgeniy Vesoli",
		date: "Born April 15th 1926 Rechista, Belarus.",
		info: "Mechanic Normandie-Nieman Regiment: Battle Of Berlin.",
		medals: [100,101, 122],
	},
	{
		id: 42,
		name: "Zinoviy Feygin",
		date: "Born April 3rd 1926 Sverdlovsk, Soviet Union.",
		info: "Radio Operator And Paratrooper Ukrainian Front, Leningrad, Liberation Of Vienna.",
		medals: [100,101,123],
	},
	{
		id: 43,
		name: "Zinoviy Rovner",
		medals: [101],
	},
	{
		id: 44,
		name: "Zinoviy Ofsei",
		date: "Born June 5th 1919 Yenakievo, Ukraine.",
		info: "Military Surgeon 13th Guards Division - Ukrainian Front.",
		medals: [101,111],
		youtube_id: "bsTXUP0Ja00",
	},
	{
		id: 45,
		name: "Zinoviy Rogov",
		date: "Born July 28th 1928 Leningrad, Soviet Union.",
		info: "Child During Siege Of Leningrad - Dug Defensive Trenches",
		medals: [100,101],
	},
	// SPECIAL CASES
	// Add a boolean column to vets to distinguish this group
	{
		id: 46,
		name: "Georgy Zhukov",
		info: "1896 - 1974 Marshal Of The Soviet Union",
		medals: [100],
		leader: true,
		copyright: "1945-2010info.com",
	},
	{
		id: 47,
		name: "Seymon Budyonny",
		date: "1883 - 1973",
		info: "Marshal Of The Soviet Union",
		medals: [100],
		leader: true,
		copyright: "wikipedia.org",
	},
	{
		id: 48,
		name: "Ivan Konev",
		date: "1897 - 1973",
		info: "Marshal Of The Soviet Union",
		medals: [100],
		leader: true,
		copyright: "wikipedia.org",
	},
	{
		id: 49,
		name: "Aleksandr Vasilevsky",
		info: "1895 - 1977 Red Army Chief Of General Staff.",
		medals: [100],
		leader: true,
		copyright: "ww2db.com",
	},
	{
		id: 50,
		name: "Joseph Stalin",
		date: "1878 - 1953",
		info: "General Secretary Of The Soviet Union.",
		medals: [100],
		leader: true,
		copyright: "biography.com",
	},
	{
		id: 54,
		name: "Andrey Vlasov",
		leader: true,
		info: "1901 - 1946 Soviet General Who Defected To Nazis",
		medals: [],
		copyright: "modern.az",
	},
	{
		id: 55,
		name: "Solomon Mikhoels",
		date: "1890 - 1948",
		info: "Director of the Jewish Anti Fascist Committe",
		medals: [120],
	},
];